application:
  sender: SherlockDocs <invitation@sherlockdocs.com>  

development:    
  files_path: files/
  templates_path: templates/
  chargify:
    subdomain: sherlockdocs-test
    api_key: dBT3aLoe-aITP9hckTPV
    shared_site_key: 5pw6dtHeJUzxRk87SNzN

test:
  files_path: tmp/files/
  templates_path: templates/  
  chargify:
    subdomain: sherlockdocs-test
    api_key: dBT3aLoe-aITP9hckTPV
    shared_site_key: 5pw6dtHeJUzxRk87SNzN

production:  
  files_path: files/
  templates_path: templates/  
  chargify:
    subdomain: sherlockdocs
    api_key: dBT3aLoe-aITP9hckTPV
    shared_site_key: CPHbAq-pO8M7HXTFsGAt

